#!/usr/bin/env python3
"""Generate MCP resource docs from canonical skill reference files.

Reads skill references and produces concise, MCP-oriented markdown
files that the mcp-bash bundle can expose as MCP resources. Outputs
are deterministic so CI can detect drift.

Usage:
    python3 scripts/sync_skill_docs_to_mcp.py [--check]

Flags:
    --check   Exit non-zero if generated files differ from committed
              versions (for CI freshness enforcement).
"""

import hashlib
import re
import sys
import textwrap
from pathlib import Path
from typing import List

REPO_ROOT: Path = Path(__file__).resolve().parent.parent
SKILL_REFS: Path = (
    REPO_ROOT
    / "skills"
    / "geekmagic-smalltv-ultra"
    / "references"
)
MCP_RESOURCES_DIR: Path = (
    REPO_ROOT / "mcp" / "smalltv-local" / "resources"
)

GENERATED_HEADER: str = (
    "<!-- AUTO-GENERATED by scripts/sync_skill_docs_to_mcp.py"
    " — do not edit manually -->\n\n"
)


def _extract_sections(
    text: str,
    headings: List[str],
) -> str:
    """Extract markdown sections whose heading matches any in headings."""
    blocks: List[str] = []
    lines: List[str] = text.splitlines(keepends=True)
    capturing: bool = False
    capture_level: int = 0

    for line in lines:
        heading_match = re.match(r"^(#{1,6})\s+(.+)", line)
        if heading_match:
            level: int = len(heading_match.group(1))
            title: str = heading_match.group(2).strip()
            if any(h.lower() in title.lower() for h in headings):
                capturing = True
                capture_level = level
                blocks.append(line)
                continue
            if capturing and level <= capture_level:
                capturing = False
        if capturing:
            blocks.append(line)

    return "".join(blocks).strip()


def generate_api_reference() -> str:
    """Produce a concise API reference from device-reference.md."""
    source: Path = SKILL_REFS / "device-reference.md"
    text: str = source.read_text(encoding="utf-8")

    sections: str = _extract_sections(
        text,
        [
            "Complete HTTP API Reference",
            "JSON Data Endpoints",
            "File Management API",
            "Web Console Pages",
            "Display Themes Detail",
        ],
    )

    return GENERATED_HEADER + textwrap.dedent("""\
        # SmallTV Ultra — API Reference (MCP Resource)

        Extracted from `skills/geekmagic-smalltv-ultra/references/\
device-reference.md`.

        """) + sections + "\n"


def generate_safety_guide() -> str:
    """Produce a safety/constraints guide from skill sources."""
    device_ref: Path = SKILL_REFS / "device-reference.md"
    device_text: str = device_ref.read_text(encoding="utf-8")

    skill_md: Path = (
        SKILL_REFS.parent / "SKILL.md"
    )
    skill_text: str = skill_md.read_text(encoding="utf-8")

    destructive_section: str = _extract_sections(
        device_text,
        [
            "System Commands",
            "WiFi Configuration",
        ],
    )

    safety_section: str = _extract_sections(
        skill_text,
        [
            "Critical Safety Rules",
            "Safe Read-Only Endpoints",
            "WiFi Recovery",
        ],
    )

    capabilities_section: str = _extract_sections(
        device_text,
        [
            "Capabilities Summary",
            "ESP8266 Constraints",
        ],
    )

    return GENERATED_HEADER + textwrap.dedent("""\
        # SmallTV Ultra — Safety and Constraints Guide (MCP Resource)

        Extracted from skill references and SKILL.md.

        """) + "\n\n".join(
        filter(None, [
            safety_section,
            destructive_section,
            capabilities_section,
        ])
    ) + "\n"


def _file_hash(path: Path) -> str:
    if not path.exists():
        return ""
    return hashlib.sha256(
        path.read_bytes()
    ).hexdigest()


def main() -> None:
    check_mode: bool = "--check" in sys.argv

    MCP_RESOURCES_DIR.mkdir(parents=True, exist_ok=True)

    outputs: dict[str, str] = {
        "api-reference.md": generate_api_reference(),
        "safety-guide.md": generate_safety_guide(),
    }

    stale: List[str] = []

    for filename, content in outputs.items():
        target: Path = MCP_RESOURCES_DIR / filename
        old_hash: str = _file_hash(target)
        new_hash: str = hashlib.sha256(
            content.encode("utf-8")
        ).hexdigest()

        if check_mode:
            if old_hash != new_hash:
                stale.append(filename)
        else:
            target.write_text(content, encoding="utf-8")
            status: str = (
                "updated" if old_hash != new_hash else "unchanged"
            )
            print(f"  {filename}: {status}")

    if check_mode:
        if stale:
            print(
                "ERROR: Generated MCP docs are stale: "
                + ", ".join(stale),
                file=sys.stderr,
            )
            print(
                "Run: python3 scripts/"
                "sync_skill_docs_to_mcp.py",
                file=sys.stderr,
            )
            sys.exit(1)
        else:
            print("OK: Generated MCP docs are up to date.")
    else:
        print(
            f"Wrote {len(outputs)} files to "
            f"{MCP_RESOURCES_DIR.relative_to(REPO_ROOT)}"
        )


if __name__ == "__main__":
    main()
